name: Build Docker Image

on:
  workflow_call:
    inputs:
      runs_on:
        description: 'Runner to execute the workflow'
        required: true
        type: string
      image_tags:
        description: 'Docker image tags (comma-separated)'
        required: true
        type: string
      release_tag:
        description: 'Release tag to use for the image'
        required: true
        type: string

jobs:
  build-image:
    runs-on: ${{ inputs.runs_on }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Harbor Registry
        uses: docker/login-action@v3
        with:
          registry: harbor.fintechsys.net
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ inputs.image_tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
